function interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag)

figure('Name','Comparator cu reactie pozitiva',...
           'Numbertitle','off',...
           'Color','B',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.85 0.75],...
           'Tag','interfataCOMP');
       
          
    
          
%------------------------ 
RadioGroup1 = uibuttongroup('Visible','on',...
                     'BackgroundColor',[0.9 0.9 0.7],...
                     'ForegroundColor','red',...
                     'Title','Parametrii circuit',...
                     'FontSize',20,...
                     'TitlePosition','centertop',...
                     'FontName','Times New Roman',...
                     'Tag','radiobutton',...
                     'Position',[0.02 0.7 0.2 0.3]);
      uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','red',...
                'Position',[0.5 0.8 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',R1,...
                'Callback','R1=str2num(get(gco,''string''));close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag)',...
                'Parent',RadioGroup1);
     uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','red',...
                'Position',[0.5 0.6 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',Rp,...
                'Callback','Rp=str2num(get(gco,''string''));close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                'Parent',RadioGroup1);
     uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','red',...
                'Position',[0.5 0.40 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',Ep,...
                'Callback','Ep=str2num(get(gco,''string''));close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                'Parent',RadioGroup1);
     uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','red',...
                'Position',[0.5 0.20 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',En,...
                'Callback','En=str2num(get(gco,''string''));close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...  
                'Parent',RadioGroup1);
 RadioGroup2 = uibuttongroup('Visible','on',...
                     'BackgroundColor',[0.9 0.9 0.7],...
                     'ForegroundColor','blue',...
                     'Title','Parametrii semnal',...
                     'FontSize',20,...
                     'TitlePosition','centertop',...
                     'FontName','Times New Roman',...
                     'Tag','radiobutton',...
                     'Position',[0.02 0.45 0.2 0.25]);
            %inserare parametrii de intrare
       txt=[' R1[ohm]  Rp[ohm]  Ep[V]    En[V]   '];
   for k=1:4
    B_T(k)=uicontrol('Style','text', ...
                  'Units','normalized', ...
                  'BackgroundColor',[0.9 0.9 0.7],...
                  'Position',[0.033 0.90-0.05.*(k-1) 0.09 0.04], ...
                  'FontSize',13,...
                  'FontWeight','bold',...
                  'FontName','Times New Roman',...
                  'String',txt((9.*(k-1))+1:9.*k), ...
                  'Callback','close; ');
   end
   
B_E7=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.05 0.65 0.3 0.3],...
 'backgroundcolor',[0.9 0.9 0.7],...
 'foregroundcolor','black',...
 'FontSize',16,...
 'FontWeight','bold',...
 'FontName','Times New Roman',...
 'String','A[V]',...
 'Parent',RadioGroup2);
                B_E7= uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','blue',...
                'Position',[0.4 0.8 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',A,...
                'Callback','A=str2num(get(gco,''string''));interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                'Parent',RadioGroup2);

B_E9=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.05 0.15 0.3 0.3],...
 'backgroundcolor',[0.9 0.9 0.7],...
 'foregroundcolor','black',...
 'FontSize',12,...
 'FontWeight','bold',...
 'FontName','Times New Roman',...
 'String','Perioada',...
 'Parent',RadioGroup2);
             B_E9= uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor',[1 1 0.9],...
                'foregroundcolor','blue',...
                'Position',[0.4 0.3 0.5 0.15],...
                'FontSize',15,...
                'FontWeight','bold',...
                'FontName','Times New Roman',...
                'String',N,...
                'Callback','N=str2num(get(gco,''string''));close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                'Parent',RadioGroup2);
        
Panel=uipanel('Visible','on',...
                     'BackgroundColor',[0.9 0.9 0.7],...
                     'ForegroundColor','black',...
                     'foregroundcolor','GREEN',...
                     'Title','COMPARATOARE',...
                     'FontSize',20,...
                     'TitlePosition','centertop',...
                     'FontName','Script',...
                     'Position',[0.25 0.5 0.25 0.4]);
                 PopString1={'COMPARATOR CU RP NEINVERSOR','COMPARATORCU RP INVERSOR'};
uicontrol('style','popup',...
          'units','normalized',...
          'position',[0.08 0.2 0.8 0.10],...
          'value',caz,...
          'string',PopString1,...
          'callback','caz=get(gco,''value''),close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
          'Parent',Panel);

CheckB=uicontrol('Style','checkbox',...
                  'Units','normalized',...
                  'BackgroundColor',[0.9 0.9 0.7],...
                  'ForegroundColor','black',...
                  'Position',[0.3 0.75 0.6 0.15],...
                  'String','Adauga  Vref',...
                  'value',b,...
                  'Tag','checkbox',...
                  'Callback','b=get(gco,''value''),close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                  'Parent',Panel);
             
Buton=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'BackgroundColor',[0.9 0.9 0.9],...
 'Position',[0.87 0.02 0.11 0.05],...
 'String','CLOSE',...
 'Callback','close');

RadioGroup = uibuttongroup('Visible','on',...
                     'BackgroundColor',[0.9 0.9 0.7],...
                     'ForegroundColor','black',...
                     'foregroundcolor','green',...
                     'Title','Tipul semnalului de intrare:',...
                     'FontSize',10,...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.15 0.4 0.7 0.3],...
                     'Parent',Panel);
                CheckB1=uicontrol('Style','checkbox',...
                  'Units','normalized',...
                  'BackgroundColor',[0.9 0.9 0.7],...
                  'ForegroundColor','black',...
                  'Position',[0.2 0.55 0.5 0.4],...
                  'String','Sinusoidal',...
                  'value',tip,...
                  'Tag','checkbox',...
                  'Callback','tip=1,close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                  'Parent',RadioGroup);
                CheckB2=uicontrol('Style','checkbox',...
                  'Units','normalized',...
                  'BackgroundColor',[0.9 0.9 0.7],...
                  'ForegroundColor','black',...
                  'Position',[0.2 0.15 0.5 0.4],...
                  'String','Triunghiular',...
                  'value',tip,...
                  'Tag','checkbox',...
                  'Callback','tip=2,close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);',...
                  'Parent',RadioGroup);
  %inserarea imaginii           
             
            
              if caz==1
                 Img=imread('cinci.jpg');
             end
             if caz==2
                 Img=imread('sapte.jpg');

             end
              if caz==1&&b==1
                 Img=imread('sase.jpg');
  
             end
             if caz==2&&b==1
                 
                 Img=imread('opt.jpg');
                 
             end

            
              image(Img);
    axis off;
    set(gca,'Position',[0.57 0.5 0.40 0.40]);
 %alegere semnal  
if tip==1
    set(CheckB1,'value',1);
    set(CheckB2,'value',0);
else
    set(CheckB1,'value',0);
    set(CheckB2,'value',1);
end


t=-1:T./100:(-1+N).*T;
    nt=length(t);
    w=2*pi./T;
    if tip==1
    ui=A.*sin(w.*t);
    end
    if tip==2
    ui=2.*A.*asin(sin(w.*t))./pi;
    end

uo=zeros(1,nt);


    switch caz
        
        
        case 1
            % Comp RP neinveror 
             Vps=Ep.*R1./(R1+Rp);
             Vpj=-Vps;
             prag=Vps;
   
            for k=1:nt

             uo(k)=Ep;
            if ui(k)>prag
            uo(k)=En;
            prag=Vpj;
           elseif ui(k)<prag
            uo(k)=Ep;
            prag=Vps;
            end
            end
            l=Vps-Vpj; 
%             

            
            case 2
               % Comp RP neinveror 
            Vps=Ep.*R1./Rp;
            Vpj=-Vps;
          prag=Vps;
     
        for k=1:nt
             uo(k)=En;
         if ui(k)>prag
           uo(k)=Ep;
           prag=Vpj;
          elseif ui(k)<prag
           uo(k)=En;
           prag=Vps;
         end
        end
        l=Vps-Vpj;   
        
    end

        if caz==1&&b==1
            
             %Comp RP neinversor si Vref
BtC=uicontrol('Style','text',...
              'Units','normalized',...
              'Position', [0.05 0.71 0.05 0.04],...
              'backgroundcolor', [0.9 0.9 0.7] ,...
              'foregroundcolor','blue',...
              'fontweight', 'bold',...
              'fontsize', 12,...
              'String','Vref[V]');
          
BeC=uicontrol('Style','edit',...
             'Units','normalized',...
             'Position', [0.12 0.71 0.1 0.04],...
             'backgroundcolor',  [0.9 0.9 0.9],...
             'foregroundcolor','blue',...
             'fontweight', 'bold',...
             'fontsize', 12,...
             'String', Vref,...
             'Callback','Vref=str2num(get(gco,''string'')),close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);');
         
          Vps=Ep.*R1./(R1+Rp)+Vref.*Rp./(R1+Rp);
          Vpj=Vref.*Rp./(R1+Rp)-Ep.*R1./(R1+Rp);
          prag=Vps;
   
         for k=1:nt

          if ui(k)>prag
            uo(k)=En;
            prag=Vpj;
           elseif ui(k)<prag
            uo(k)=Ep;
            prag=Vps;
          end
         end
          l=Vps-Vpj;
          
         end

        if caz==2&&b==1
            
             %Comp RP neinversor si Vref
            
BtC=uicontrol('Style','text',...
              'Units','normalized',...
              'Position', [0.05 0.71 0.05 0.04],...
              'backgroundcolor', [0.9 0.9 0.7] ,...
              'foregroundcolor','blue',...
              'fontweight', 'bold',...
              'fontsize', 12,...
              'String','Vref[V]');
BeC=uicontrol('Style','edit',...
             'Units','normalized',...
             'Position', [0.12 0.71 0.1 0.04],...
             'backgroundcolor',  [0.9 0.9 0.9],...
             'foregroundcolor','blue',...
             'fontweight', 'bold',...
             'fontsize', 12,...
             'String', Vref,...
             'Callback','Vref=str2num(get(gco,''string'')),close;interfataCOMP(b,caz,tip,R1,Rp,A,Ep,En,N,T,Vref,prag);');

          Vps=(Ep.*R1./Rp)+Vref.*R1./(R1+Rp);
          Vpj=Vref.*R1./(R1+Rp)-Ep.*R1./Rp;
          prag=Vps;
  
        for k=1:nt
             
         if ui(k)>prag
           uo(k)=Ep;
          prag=Vpj;
          elseif ui(k)<prag;
           uo(k)=En;
           prag=Vps;
         end
        end
          l=Vps-Vpj;   
          
        end

   
       
    subplot(3,3,7);  % Tensiunea de intrare 
   
    tp=asin(Vps/A)/w;
    
    tp1=asin(Vpj/A)/w;
    plot(t,ui,'r',t,Vps,'k',tp,Vps,'kp',t,Vpj,'k',tp1,Vpj,'rp');      %afiseaza pe ui si pargurile

    grid on;
    title('SEMNALUL DE INTRARE ','FontSize',15,'FontWeight','demi');
    ylabel('Tensiunea de intrare [V]');
    xlabel('Timpul [s]');
    
    subplot(3,3,8); % Tensiunea de iesire 
    plot(t,uo,'b');
    grid on;
    title(' SEMNALUL DE IESIRE ','FontSize',15,'FontWeight','demi');
    ylabel(' Tensiunea de iesire [V]');
    xlabel('Timpul [s]');
    
%--------------------------------------------

% Tensiunea de iesire in functie de tensiunea de intrare


    subplot(3,3,9); 
    
    plot(ui,uo,'g',Vps,0,'kp',Vpj,0,'rp');grid on;

    title('Caracteristica Uo-Ui','FontSize',15,'FontWeight','demi');
    ylabel(' Uo [V]');
    xlabel('Tensiunea de intrare Ui [V]');
    